const els={industry:document.querySelector('#industry'),city:document.querySelector('#city'),radius:document.querySelector('#radius'),minScore:document.querySelector('#minScore'),search:document.querySelector('#searchBtn'),results:document.querySelector('#results'),count:document.querySelector('#count'),label:document.querySelector('#queryLabel'),export:document.querySelector('#exportBtn'),clear:document.querySelector('#clearBtn')};
const configs={
 bakery:{label:'Bäckerei',query:'shop=bakery',base:5},restaurant:{label:'Gastronomie',query:'amenity=restaurant',base:4},hotel:{label:'Hotel',query:'tourism=hotel',base:5},butcher:{label:'Metzgerei',query:'shop=butcher',base:4},car_repair:{label:'Werkstatt',query:'shop=car_repair',base:4},car_dealer:{label:'Autohaus',query:'shop=car',base:3},fitness:{label:'Fitnessstudio',query:'leisure=fitness_centre',base:4},supermarket:{label:'Supermarkt',query:'shop=supermarket',base:5},retail:{label:'Einzelhandel',query:'shop=clothes',base:2},craft:{label:'Handwerk',query:'craft=*',base:3},industrial:{label:'Produktion / Industrie',query:'landuse=industrial',base:5},all:{label:'Alle Gewerbe',query:'',base:3}
};
let leads=[];
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
async function geocode(city){const url=`https://photon.komoot.io/api/?q=${encodeURIComponent(city)}&limit=1`;const r=await fetch(url);if(!r.ok)throw Error('Ort konnte nicht gefunden werden');const d=await r.json();if(!d.features?.length)throw Error('Ort konnte nicht gefunden werden');const [lon,lat]=d.features[0].geometry.coordinates;return {lat,lon};}
function queryFor(cfg,lat,lon,radius){const around=`(around:${radius},${lat},${lon})`;if(cfg.query==='craft=*')return `[out:json][timeout:35];(nwr[craft]${around};);out center tags;`;if(!cfg.query)return `[out:json][timeout:35];(nwr[shop]${around};nwr[amenity]${around};nwr[tourism]${around};nwr[craft]${around};);out center tags;`;const [k,v]=cfg.query.split('=');return `[out:json][timeout:35];(nwr[${k}${v==='*'?'':`="${v}"`}]${around};);out center tags;`;}
async function overpass(q){const endpoints=['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter'];for(const e of endpoints){try{const r=await fetch(e,{method:'POST',body:q});if(r.ok)return await r.json()}catch(e){}}throw Error('Die freie Kartendatenbank ist gerade nicht erreichbar. Bitte erneut versuchen.');}
function score(tags,cfg){let s=cfg.base;const text=Object.values(tags||{}).join(' ').toLowerCase();if(tags?.['addr:housenumber'])s+=0.2;if(tags?.website||tags?.contact?.website)s+=0.3;if(/gmbh|ag|kg|holding|group/.test(text))s+=0.7;if(/filiale|filialen|standorte/.test(text))s+=0.4;if(cfg.label==='Produktion / Industrie')s=5;return Math.max(1,Math.min(5,Math.round(s)));}
function normalize(el,cfg){const t=el.tags||{};const lat=el.lat??el.center?.lat,lon=el.lon??el.center?.lon;if(lat==null||lon==null)return null;const name=t.name||t['brand']||'Unbenanntes Unternehmen';let website=t.website||t['contact:website']||'';if(website&&!/^https?:\/\//i.test(website))website='https://'+website;const address=[t['addr:street'],t['addr:housenumber'],t['addr:postcode'],t['addr:city']].filter(Boolean).join(' ');return {name,address,website,phone:t.phone||t['contact:phone']||'',industry:cfg.label,lat,lon,score:score(t,cfg)};}
function render(){const min=Number(els.minScore.value);const filtered=leads.filter(x=>x.score>=min).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name,'de'));els.count.textContent=filtered.length;els.export.disabled=!filtered.length;els.results.innerHTML=filtered.length?filtered.map((x,i)=>`<article class="lead"><div class="leadMain"><div class="leadTitle">${esc(x.name)} <span class="badge">${esc(x.industry)}</span></div><div class="meta"><span>${esc(x.address||'Adresse nicht erfasst')}</span>${x.phone?`<span>${esc(x.phone)}</span>`:''}</div><div class="links">${x.website?`<a href="${esc(x.website)}" target="_blank" rel="noopener">Website ↗</a>`:''}<a href="https://www.google.com/maps/search/?api=1&query=${x.lat},${x.lon}" target="_blank" rel="noopener">Maps ↗</a></div></div><div class="score"><div class="flames">${'🔥'.repeat(x.score)}${'·'.repeat(5-x.score)}</div><strong>${x.score}/5 Energiepotenzial</strong></div></article>`).join(''):`<div class="empty"><div class="emptyIcon">⌕</div><h2>Keine passenden Leads</h2><p>Ändere Branche, Radius oder Mindestpotenzial.</p></div>`;}
function setLoading(on){els.search.disabled=on;els.search.querySelector('span').textContent=on?'Suche läuft …':'Leads finden';}
els.search.addEventListener('click',async()=>{const city=els.city.value.trim();if(!city)return alert('Bitte einen Ort eingeben.');setLoading(true);try{const cfg=configs[els.industry.value],geo=await geocode(city);const data=await overpass(queryFor(cfg,geo.lat,geo.lon,Number(els.radius.value)));leads=(data.elements||[]).map(x=>normalize(x,cfg)).filter(Boolean).filter((x,i,a)=>a.findIndex(y=>y.name===x.name&&Math.abs(y.lat-x.lat)<.0001&&Math.abs(y.lon-x.lon)<.0001)===i).slice(0,250);els.label.textContent=`· ${cfg.label} · ${city}`;render();}catch(e){alert(e.message||'Suche fehlgeschlagen');}finally{setLoading(false);}});
els.minScore.addEventListener('change',render);
els.clear.addEventListener('click',()=>{leads=[];els.count.textContent='0';els.label.textContent='';els.export.disabled=true;els.results.innerHTML='<div class="empty"><div class="emptyIcon">⌕</div><h2>Noch keine Leads</h2><p>Starte eine Suche, zum Beispiel „Bäckerei · Mainz · 50 km“.</p></div>';});
els.export.addEventListener('click',()=>{const min=Number(els.minScore.value);const rows=leads.filter(x=>x.score>=min);const header=['Unternehmen','Branche','Adresse','Telefon','Website','Energiepotenzial','Latitude','Longitude'];const csv=[header,...rows.map(x=>[x.name,x.industry,x.address,x.phone,x.website,x.score,x.lat,x.lon])].map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';')).join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='cpm-gewerbeleads.csv';a.click();URL.revokeObjectURL(a.href);});
