const els={industry:document.querySelector('#industry'),city:document.querySelector('#city'),radius:document.querySelector('#radius'),minScore:document.querySelector('#minScore'),search:document.querySelector('#searchBtn'),results:document.querySelector('#results'),count:document.querySelector('#count'),label:document.querySelector('#queryLabel'),export:document.querySelector('#exportBtn'),clear:document.querySelector('#clearBtn')};
const configs={bakery:{label:'Bäckerei',query:'shop=bakery',base:5},restaurant:{label:'Gastronomie',query:'amenity=restaurant',base:4},hotel:{label:'Hotel',query:'tourism=hotel',base:5},butcher:{label:'Metzgerei',query:'shop=butcher',base:4},car_repair:{label:'Werkstatt',query:'shop=car_repair',base:4},car_dealer:{label:'Autohaus',query:'shop=car',base:3},fitness:{label:'Fitnessstudio',query:'leisure=fitness_centre',base:4},supermarket:{label:'Supermarkt',query:'shop=supermarket',base:5},retail:{label:'Einzelhandel',query:'shop=clothes',base:2},craft:{label:'Handwerk',query:'craft=*',base:3},industrial:{label:'Produktion / Industrie',query:'landuse=industrial',base:5},all:{label:'Alle Gewerbe',query:'',base:3}};
const STATUSES=['Neu','Recherche','Kontaktversuch','Gespräch','Kein Interesse','Abschluss'];const storeKey='cpm-leads-v2';let leads=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const db=()=>{try{return JSON.parse(localStorage.getItem(storeKey)||'{}')}catch{return {}}};
function meta(id){return db()[id]||{status:'Neu',contact:'',note:''}}function saveMeta(x){const d=db();d[x.id]={status:x.status,contact:x.contact,note:x.note};localStorage.setItem(storeKey,JSON.stringify(d));}
async function geocode(city){const r=await fetch(`https://photon.komoot.io/api/?q=${encodeURIComponent(city)}&limit=1`);if(!r.ok)throw Error('Ort konnte nicht gefunden werden');const d=await r.json();if(!d.features?.length)throw Error('Ort konnte nicht gefunden werden');const [lon,lat]=d.features[0].geometry.coordinates;return{lat,lon}}
function queryFor(c,lat,lon,r){const a=`(around:${r},${lat},${lon})`;if(c.query==='craft=*')return`[out:json][timeout:35];nwr[craft]${a};out center tags;`;if(!c.query)return`[out:json][timeout:35];(nwr[shop]${a};nwr[amenity]${a};nwr[tourism]${a};nwr[craft]${a};);out center tags;`;const[k,v]=c.query.split('=');return`[out:json][timeout:35];nwr[${k}${v==='*'?'':`="${v}"`}]${a};out center tags;`}
async function overpass(q){for(const e of ['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter'])try{const r=await fetch(e,{method:'POST',body:q,headers:{'Content-Type':'text/plain'}});if(r.ok)return r.json()}catch{}throw Error('Kartendatenbank momentan nicht erreichbar. Bitte erneut versuchen.')}
function score(t,c){let s=c.base,text=Object.values(t||{}).join(' ').toLowerCase();if(t?.['addr:housenumber'])s+=.2;if(t?.website||t?.['contact:website'])s+=.3;if(/gmbh|ag|kg|holding|group/.test(text))s+=.7;if(/filiale|filialen|standorte/.test(text))s+=.4;if(c.label==='Produktion / Industrie')s=5;return Math.max(1,Math.min(5,Math.round(s)))}
function normalize(e,c){const t=e.tags||{},lat=e.lat??e.center?.lat,lon=e.lon??e.center?.lon;if(lat==null||lon==null)return null;let website=t.website||t['contact:website']||'';if(website&&!/^https?:\/\//i.test(website))website='https://'+website;const id=`${t.name||t.brand||'Unbenanntes Unternehmen'}|${lat.toFixed(5)}|${lon.toFixed(5)}`,m=meta(id);return{id,name:t.name||t.brand||'Unbenanntes Unternehmen',address:[t['addr:street'],t['addr:housenumber'],t['addr:postcode'],t['addr:city']].filter(Boolean).join(' '),website,phone:t.phone||t['contact:phone']||'',industry:c.label,lat,lon,score:score(t,c),...m}}
function research(x){const q=encodeURIComponent(`${x.name} ${x.address}`),domain=x.website?encodeURIComponent(new URL(x.website).hostname):'';return`<a href="https://www.google.com/search?q=${q}" target="_blank" rel="noopener">Recherche ↗</a>${domain?`<a href="https://hunter.io/domain-search?domain=${domain}" target="_blank" rel="noopener">E-Mail prüfen ↗</a>`:''}<a href="https://www.linkedin.com/search/results/companies/?keywords=${encodeURIComponent(x.name)}" target="_blank" rel="noopener">LinkedIn ↗</a>`}
function render(){const min=+els.minScore.value,f=leads.filter(x=>x.score>=min).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name,'de'));els.count.textContent=f.length;els.export.disabled=!f.length;els.results.innerHTML=f.length?f.map(x=>`<article class="lead" data-id="${esc(x.id)}"><div class="leadMain"><div class="leadTitle">${esc(x.name)} <span class="badge">${esc(x.industry)}</span></div><div class="meta"><span>${esc(x.address||'Adresse nicht erfasst')}</span>${x.phone?`<span>${esc(x.phone)}</span>`:''}</div><div class="links">${x.website?`<a href="${esc(x.website)}" target="_blank" rel="noopener">Website ↗</a>`:''}<a href="https://www.google.com/maps/search/?api=1&query=${x.lat},${x.lon}" target="_blank" rel="noopener">Maps ↗</a>${research(x)}</div><div class="crm"><select class="statusSelect">${STATUSES.map(s=>`<option ${s===x.status?'selected':''}>${s}</option>`).join('')}</select><input class="contactInput" value="${esc(x.contact)}" placeholder="Ansprechpartner / E-Mail"><input class="noteInput" value="${esc(x.note)}" placeholder="Notiz"><button class="saveLead">Speichern</button></div></div><div class="score"><div class="flames">${'🔥'.repeat(x.score)}${'·'.repeat(5-x.score)}</div><strong>${x.score}/5 Energiepotenzial</strong></div></article>`).join(''):`<div class="empty"><div class="emptyIcon">⌕</div><h2>Keine passenden Leads</h2><p>Ändere Branche, Radius oder Mindestpotenzial.</p></div>`}
function loading(on){els.search.disabled=on;els.search.querySelector('span').textContent=on?'Suche läuft …':'Leads finden'}
els.search.addEventListener('click',async()=>{const city=els.city.value.trim();if(!city)return alert('Bitte einen Ort eingeben.');loading(true);try{const c=configs[els.industry.value],g=await geocode(city),d=await overpass(queryFor(c,g.lat,g.lon,+els.radius.value));leads=(d.elements||[]).map(e=>normalize(e,c)).filter(Boolean).filter((x,i,a)=>a.findIndex(y=>y.name===x.name&&Math.abs(y.lat-x.lat)<.0001&&Math.abs(y.lon-x.lon)<.0001)===i).slice(0,250);els.label.textContent=`· ${c.label} · ${city}`;render()}catch(e){alert(e.message||'Suche fehlgeschlagen')}finally{loading(false)}});
els.minScore.addEventListener('change',render);els.results.addEventListener('click',e=>{const card=e.target.closest('.lead');if(!card||!e.target.classList.contains('saveLead'))return;const x=leads.find(v=>v.id===card.dataset.id);x.status=card.querySelector('.statusSelect').value;x.contact=card.querySelector('.contactInput').value.trim();x.note=card.querySelector('.noteInput').value.trim();saveMeta(x);e.target.textContent='Gespeichert ✓';setTimeout(()=>e.target.textContent='Speichern',1000)});
els.clear.addEventListener('click',()=>{leads=[];els.count.textContent='0';els.label.textContent='';els.export.disabled=true;els.results.innerHTML='<div class="empty"><div class="emptyIcon">⌕</div><h2>Noch keine Leads</h2><p>Starte eine Suche.</p></div>'});
els.export.addEventListener('click',()=>{const rows=leads.filter(x=>x.score>=+els.minScore.value),head=['Unternehmen','Branche','Adresse','Telefon','Website','Energiepotenzial','Status','Ansprechpartner/E-Mail','Notiz','Latitude','Longitude'];const csv=[head,...rows.map(x=>[x.name,x.industry,x.address,x.phone,x.website,x.score,x.status,x.contact,x.note,x.lat,x.lon])].map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';')).join('\n'),blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='cpm-gewerbeleads.csv';a.click();URL.revokeObjectURL(a.href)});